bbs/apps/cms/__init__.py
from .views import bp
import apps.cms.hooks

bbs/apps/cms/views.py
from flask import Blueprint
from flask import views,render_template,request,session,redirect,url_for
from .forms import LoginForm,ResetPwdForm,RestEmailForm,UpdateBannerForm
from .models import CMSUser,CMSPersmission
from .decorators import login_required,permission_required
import config
from flask import g
from flask import jsonify
from exts import db
from utils import xjson

from exts import mail
from flask_mail import Message
from utils import xcache
import string,random
# from . import hooks

import qiniu

#轮播图管理视图
from .forms import AddBannerForm
from apps.models import BannerModel

from apps.models import BoardModel
from .forms import AddBoardForm

from .forms import UpdateBoardForm

from apps.models import HighlightPostModel, PostModel,CommentModel
from apps.front.models import FrontUser

bp = Blueprint('cms',__name__,url_prefix='/cms')

#定义一个钩子函数
@bp.before_request
def before_request():
    if config.CMS_USER_ID in session:
        user_id = session.get(config.CMS_USER_ID)
        user = CMSUser.query.get(user_id)
        if user:
            g.cms_user = user


@bp.route('/')   #路由装饰器一定要放在最上面，否则会找不到路由
@login_required
def index():
    return render_template('cms/cms_index.html')

class LoginView(views.MethodView):
    def get(self):
        return render_template('cms/cms_login.html')

    def post(self):
        login_form = LoginForm(request.form)
        if login_form.validate():
            email = login_form.email.data
            password = login_form.password.data
            remember = login_form.password.data
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    #如果勾选了记住我，则保存session，这样就算浏览器关闭session还是存在的
                    session.permanent = True
                return redirect(url_for('cms.index')) #因为是蓝图这里必须使用cms.index,不能使用index
            else:
                return render_template('cms/cms_login.html',message='账号或密码错误')
                #等同于 return self.get(message='账号或密码错误')
        else:
            message = login_form.errors.popitem()[1][0]
            print(message)
            # return self.get(message=message)

bp.add_url_rule('/login/',view_func=LoginView.as_view('login'))


#注销功能
@bp.route('/logout/')
@login_required

def logout():
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))

#个人主页功能
@bp.route('/profile')
@login_required
@permission_required(CMSPersmission.VISITOR) #这个装饰器要放在login_required下面，因为只有先登录了，才能进下一步验证
def profile():
    return render_template('cms/cms_profile.html')


#修改密码功能，直接使用类视图
class ResetPwdView(views.MethodView):
    decorators = [login_required] #修改密码也需要先登陆，这是类视图装饰器
    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        resetpwd_form = ResetPwdForm(request.form)
        if resetpwd_form.validate():
            oldpwd = resetpwd_form.oldpwd.data
            newpwd = resetpwd_form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                #因为接受是ajax,所以这里使用jsonify返回数据
                #返回code字段表示状态码，message信息提示
                # return jsonify({"code":200,"message":"修改成功"})
                return xjson.json_sucess('修改成功')
            else:
                # return jsonify({"code":400,"message":"原密码错误"})
                return xjson.json_params_error('原密码错误')
        else:
            message = resetpwd_form.get_error()
            # return jsonify({"code":400,"message":message})
            return xjson.json_params_error(message)

bp.add_url_rule('/resetpwd/',view_func=ResetPwdView.as_view('resetpwd'))



#修改邮箱视图
class ResetEmailView(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetemail.html')

    def post(self):
        resetemail_form = RestEmailForm(request.form)
        if resetemail_form.validate():
            email = resetemail_form.email.data
            g.cms_user.email = email
            db.session.commit()
            return xjson.json_sucess('邮箱修改成功')
        else:
            message = resetemail_form.get_error()
            return xjson.json_params_error(message)


bp.add_url_rule('/resetemail/',view_func=ResetEmailView.as_view('resetemail'))



#测试邮件视图
@bp.route('/test_email/')
def test_email():
    msg = Message(
        'Flask项目测试邮件',  # 这是邮件主题
        sender='',
        recipients=[''],  # 发送给谁，这是个列表，可以有多个接收者
        body='Hello, 这是一封测试邮件，这是邮件的正文'
    )
    mail.send(msg) #发送
    return 'success'



#前端请求生成验证码视图
@bp.route('/email_captcha/')
@login_required
def email_captcha():
    #/cms/email_capthcha/?email=xxx@qq.com
    email = request.args.get('email')
    print(email)
    if not email:
        return xjson.json_params_error('请传递邮件参数！')

    #生成6位数的随机验证码
    source = list(string.ascii_letters)
    source.extend(map(lambda x:str(x),range(0,10)))
    captcha = ''.join(random.sample(source,6))

    #发送邮件
    msg = Message('BBS论坛更换邮箱验证码',
                  recipients=[email],
                  body='您的验证码：{},5分钟内邮箱'.format(captcha)
                  )
    try:
        mail.send(msg)
    except Exception as err:
        print(err)
        return xjson.json_server_error(message='邮件发送失败')


    #验证码存入memcached
    xcache.set(email,captcha)
    return xjson.json_sucess(message='邮件发送成功')


##帖子管理
@bp.route('/posts/')
@login_required
@permission_required(CMSPersmission.POSTER)
def posts():
    post_list = PostModel.query.all()
    return render_template('cms/cms_posts.html', posts=post_list)

@bp.route('/hpost/',methods=['POST'])
@login_required
@permission_required(CMSPersmission.POSTER)
def hpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return xjson.json_param_error('请传入帖子id！')
    post = PostModel.query.get(post_id)
    if not post:
        return xjson.json_param_error("没有这篇帖子！")

    highlight = HighlightPostModel()
    highlight.post = post
    db.session.add(highlight)
    db.session.commit()
    return xjson.json_success()


@bp.route('/uhpost/',methods=['POST'])
@login_required
@permission_required(CMSPersmission.POSTER)
def uhpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return xjson.json_param_error('请传入帖子id！')
    post = PostModel.query.get(post_id)
    if not post:
        return xjson.json_param_error("没有这篇帖子！")

    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return xjson.json_success()

#评论管理
@bp.route('/comments/')
@login_required
@permission_required(CMSPersmission.COMMENTER)
def comments():
    comments = CommentModel.query.all()
    return render_template('cms/cms_comments.html')

#前台用户管理
@bp.route('/fusers/')
@login_required
@permission_required(CMSPersmission.FRONTUSER)
def fusers():
    fusers = FrontUser.query.all()
    return render_template('cms/cms_fusers.html')

#cms用户管理
@bp.route('/cusers/')
@login_required
@permission_required(CMSPersmission.CMSUSER)
def cusers():
    cuser = CMSUser.query.all()
    print(cuser[0].roles[0].name)
    return render_template('cms/cms_cusers.html')


#cms组管理
@bp.route('/croles/')
@login_required
@permission_required(CMSPersmission.ADMIN)
def croles():
    return render_template('cms/cms_roles.html')

#展示轮播图
@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html',banners=banners)


@bp.route('/abanner/',methods=['POST'])
@login_required
def abanner():
    form = AddBannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name,image_url=image_url,link_url=link_url,priority=priority)
        db.session.add(banner)
        db.session.commit()
        return xjson.json_success()
    else:
        return xjson.json_param_error(message=form.get_error())



@bp.route('/ubanner/',methods=['POST'])
@login_required
def ubanner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url

            banner.priority = priority
            db.session.commit()
            return xjson.json_success()
        else:
            return xjson.json_param_error(message='没有这个轮播图！')
    else:
        return xjson.json_param_error(message=form.get_error())

@bp.route('/dbanner/',methods=['POST'])
@login_required
def dbanner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return xjson.json_param_error(message='请传入轮播图id！')

    banner = BannerModel.query.get(banner_id)
    if not banner:
        return xjson.json_param_error(message='没有这个轮播图！')

    db.session.delete(banner)
    db.session.commit()
    return xjson.json_success()


@bp.route('/uptoken/')
def uptoken():
    access_key = '4pMtV3F2eWZWv0TSD3DXjhcmlmVpxOCLvIdM8aF7'
    secret_key = 'GsmHmllZkpxOh5VAkzGrSSjCL7MQGZraQhtYmE-O'
    q = qiniu.Auth(access_key,secret_key)

    bucket = 'flask-1903bbs'
    token = q.upload_token(bucket)
    return jsonify({'uptoken':token})

@bp.route('/aboard/', methods=['POST'])
@login_required
@permission_required(CMSPersmission.BOARDER)
def aboard():
    add_form_board = AddBoardForm(request.form)
    if add_form_board.validate():
        name = add_form_board.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()

bbs/apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    g
)

from apps.front.decorators import login_required
from .forms import SignUpForm
from .models import FrontUser
from exts import db
from utils import xjson
from utils import safeutils
import config
from .forms import SignInForm
from .forms import AddPostForm
from apps.models import BannerModel, BoardModel, PostModel
from flask_paginate import Pagination, get_page_parameter
from flask import abort

from .forms import AddCommentForm
from apps.models import CommentModel

from apps.models import HighlightPostModel
from sqlalchemy.sql import func

# from .decorators import login_required

bp = Blueprint('front', __name__)

@bp.route('/')
def index():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    boards = BoardModel.query.all()
    # comments = CommentModel.query.all()

    # 当前页面
    page = request.args.get(get_page_parameter(), type=int, default=1)
    # 开始位置
    start = (page - 1) * config.PER_PAGE
    # 结束位置
    end = start + config.PER_PAGE

    board_id = request.args.get('bd', type=int, default=None)
    # comment_id = request.args.get('bd', type=int, default=None)
    sort = request.args.get("st", type=int, default=1)
    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精的时间倒叙排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞的数量排序,点赞功能没有做，所以这里用时间倒序排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论的数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    if board_id:
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()

    # if comment_id:
    #     query_obj = query_obj.filter(PostModel.comment_id == comment_id)
    #     posts = query_obj.slice(start, end)
    #     total = query_obj.count()
    # else:
    #     posts = query_obj.slice(start, end)
    #     total = query_obj.count()


    pagination = Pagination(bs_version=3,page=page, total=total)
    context = {
        'banners': banners,
        'boards': boards,
        # 'comments':comments,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort
    }
    return render_template('front/front_index.html', **context)



class SignUpViews(views.MethodView):
    def get(self):
        return render_template('front/front_signup.html')

    def post(self):
        signup_form = SignUpForm(request.form)
        if signup_form.validate():
            telephone = signup_form.telephone.data
            username = signup_form.username.data
            password = signup_form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return xjson.json_success('恭喜您，注册成功')
        else:
            return xjson.json_params_error(signup_form.get_error())


bp.add_url_rule('/signup/', view_func=SignUpViews.as_view('signup'))


class SignInViews(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        return render_template('front/front_signin.html')


    def post(self):
        signin_form = SignInForm(request.form)
        if signin_form.validate():
            telephone = signin_form.telephone.data
            password = signin_form.password.data
            remember = signin_form.remember.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.premanent = True
                return xjson.json_success('登陆成功')
            else:
                return xjson.json_params_error('手机号或密码错误')
        else:
            return xjson.json_params_error(signin_form.get_error())

bp.add_url_rule('/signin/', view_func=SignInViews.as_view('signin'))



@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        add_post_form = AddPostForm(request.form)
        if add_post_form.validate():
            title = add_post_form.title.data
            content = add_post_form.content.data
            board_id = add_post_form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return xjson.json_param_error(message='没有这个板块')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return xjson.json_success()
        else:
            return xjson.json_param_error(message=add_post_form.get_error())

@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)

@bp.route('/comment/',methods=['POST'])
@login_required
def add_comment():
    add_comment_form = AddCommentForm(request.form)
    if add_comment_form.validate():
        content = add_comment_form.content.data
        post_id = add_comment_form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return xjson.json_success()
        else:
            return xjson.json_param_error('没有这篇帖子！')
    else:
        return xjson.json_param_error(add_comment_form.get_error())

bbs/templates/cms/base.html
{% from "common/macro.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}

    {% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ static('cms/css/cms_base.css')}}">
    <script src="{{ static('cms/js/cms_base.js') }}"></script>
    <script src="{{ url_for('static', filename='common/js/bbsajax.js') }}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}<span>[超级管理员]</span></a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                  {% if g.cms_user.has_permission(CMSPersmission.VISITOR) %}
                    <li class="profile-li">
                        <a href="#">个人中心<span></span></a>
                        <ul class="subnav">
                            <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                            <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                            <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                        </ul>
                    </li>
                  {% endif %}

              <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>

              {% if g.cms_user.has_permission(CMSPersmission.POSTER) %}
                <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
              {% endif %}

              {% if g.cms_user.has_permission(CMSPersmission.COMMENTER) %}
                <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
              {% endif %}

              {% if g.cms_user.has_permission(CMSPersmission.BOARDER) %}
                <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
              {% endif %}

              {% if g.cms_user.has_permission(CMSPersmission.FRONTUSER) %}
                <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
{#                <li class="role-manage"><a href="#">组管理</a></li>#}
              {% endif %}

              {% if g.cms_user.has_permission(CMSPersmission.CMSUSER) %}
                <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
              {% endif %}

              {% if g.cms_user.has_permission(CMSPersmission.ADMIN) %}
                <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
              {% endif %}

            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
      </div>
          </div>
    </div>
</body>
</html>

bbs/templates/cms/cms_banners.html
{% extends 'cms/base.html' %}

{% block title %}
    轮播图管理-CMS管理系统
{% endblock %}

{% block head%}
    <style>
        .top-box button{
            float: right;
        }
        .top-box{
            overflow: hidden;
            background: #ecedf0;
            padding: 10px;
        }
    </style>
    <script src="{{ url_for('static', filename='cms/js/banners.js')}}"></script>
    <script src="{{ url_for('static',filename='common/layer-v3.1.1/layer/layer.js') }}"></script>

        <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
        <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
        <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>

        <script src="{{ url_for('static', filename='common/js/bbsqiniu.js') }}"></script>
{% endblock %}

{% block page_title %}
    轮播图管理
{% endblock %}

{% block main_content %}
    这是轮播图管理页面
     <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog1">添加轮播图</button>
    </div>

    <table class="table table-bordered">
            <thead>
                <tr>
                    <th>名称</th>
                    <th>图片链接</th>
                    <th>跳转链接</th>
                    <th>优先级</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>
            </thead>

            <tbody>
                {% for banner in banners %}
{#                <tr>#}
                     <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
                    <td>{{ banner.name }}</td>
                    <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                    <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-banner-btn" id="save-banner-btn" data-toggle="modal" data-target="#banner-dialog1">编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn1">删除</button>

                        <script>
                            {#$(function (){#}
                            {#    $(".delete-banner-btn1").click(function (event){#}
                            {#        console.log('djkafgkv;alk')#}
                            {#    })#}
                            {##}
                            {#})#}
                        </script>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>



    <div class="modal fade" id="banner-dialog1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">添加轮播图</h4>
            </div>
            <div class="modal-body">

                <form action="" class="form-horizontal">
            <div class="form-group">
              <label class="col-sm-2 control-label">名称：</label>
              <div class="col-sm-10">
                  <input type="text" class="form-control" name="name" placeholder="轮播图名称">
              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label">图片：</label>
              <div class="col-sm-7">
                  <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
              </div>
              <button id="upload-btn">添加图片</button>
{#              class="btn btn-info col-sm-2" #}
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label">跳转：</label>
              <div class="col-sm-10">
                  <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
              </div>
          </div>
          <div class="form-group">
              <label class="col-sm-2 control-label">权重：</label>
              <div class="col-sm-10">
                  <input type="number" class="form-control" name="priority" placeholder="优先级">
              </div>
          </div>
        </form>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="save-banner-btn1">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>






{% endblock %}

bbs/templates/cms/cms_comments.html
{% extends 'cms/base.html' %}

{% block title %}
    评论管理-CMS管理系统
{% endblock %}

{% block page_title %}
    评论管理
{% endblock %}

{% block main_content %}
    这是评论管理页面


    <table class="table table-bordered">
        <thead>
            <tr>
                <th>评论id</th>
                <th>评论内容</th>
                <th>评论时间</th>
                <th>评论文章名称</th>
                <th>评论用户</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for com in comments %}
{#                <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">#}
{#                    <td><a target="_blank" href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a></td>#}
                    <td>{{ com.id }}</td>
                    <td>{{ com.content }}</td>
                    <td>{{ com.create_time }}</td>
                    <td>{{ com.post.title }}</td>
                    <td>{{ com.author.username }}</td>
                    <td>

{#                            <button class="btn btn-default btn-xs highlight-btn">取消加精</button>#}

{#                            <button class="btn btn-default btn-xs highlight-btn">加精</button>#}

                        <button class="btn btn-danger btn-xs">删除评论</button>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}

bbs/templates/cms/cms_posts.html
{% extends 'cms/base.html' %}

{% block title %}
    帖子管理-CMS管理系统
{% endblock %}

{% block page_title %}
    帖子管理
{% endblock %}

{% block head %}
    <script src="{{ url_for('static', filename='cms/js/posts.js')}}"></script>
{% endblock %}

{% block main_content %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>标题</th>
                <th>发布时间</th>
                <th>板块</th>
                <th>作者</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">
                    <td><a target="_blank" href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a></td>
                    <td>{{ post.create_time }}</td>
                    <td>{{ post.board.name }}</td>
                    <td>{{ post.author.username }}</td>
                    <td>
                        {% if post.highlight %}
                            <button class="btn btn-default btn-xs highlight-btn">取消加精</button>
                        {% else %}
                            <button class="btn btn-default btn-xs highlight-btn">加精</button>
                        {% endif %}
                        <button class="btn btn-danger btn-xs">移除</button>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}

bbs/templates/cms/cms_roles.html
{% extends 'cms/base.html' %}

{% block title %}
    CMS组管理-CMS管理系统
{% endblock %}

{% block page_title %}
    CMS组管理
{% endblock %}

{% block main_content %}
    这是CMS组管理页面
{% endblock %}