bbs/apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import generate_password_hash, check_password_hash
import enum
from datetime import datetime

class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4


class FrontUser(db.Model):
    __tablename__ = 'front_user'
    #这里的id如果我们还使用自动增长，就会存在商业安全隐患，用户可以根据id推算出我们网站的人数
    #不使用自动增长，又要保证id的唯一性，我们就可以使用uuid
    #虽然uuid好用，但是它太长了，查找的效率会降低
    #这时我们就可以使用shortuuid这个库，它既满足了唯一性，又没有uuid那么长
    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(11), nullable=False)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(50))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime, default=datetime.now)

    #对password对应的是_password，所以要做处理
    def __init__(self, *args, **kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop("password")
        super(FrontUser, self).__init__(*args, **kwargs)


    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self, rawpwd):
        return check_password_hash(self._password, rawpwd)

bbs/apps/front/forms.py
from apps.forms import BaseForm
from wtforms import StringField,IntegerField
from wtforms.validators import Regexp, Length, EqualTo, ValidationError,InputRequired
from utils import xcache
from .models import FrontUser


class SignUpForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[35678]\d{9}', message='手机号码格式错误')])
    sms_captcha = StringField(validators=[Regexp(r'\w{6}', message='短信验证码错误')])
    username = StringField(validators=[Length(2,20, message='用户名格式错误')])
    password1 = StringField(validators=[Length(5, 30, message='密码格式错误')])
    password2 = StringField(validators=[EqualTo('password1', message='两次密码不一致')])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message='图形验证码错误')])

    def validate_telephone(self, field):
        user = FrontUser.query.filter_by(telephone=field.data).first()
        if user:
            raise ValidationError('该手机号已被注册')

    def validate_sms_captcha(self, field):
        telephone = self.telephone.data
        sms_captcha = field.data
        xcache.set('13297554024', 'luck')
        sms_captcha_mem = xcache.get(telephone)
        print('用户输入的验证码：{}'.format(sms_captcha))
        print( '服务器存储的验证码：{}'.format(sms_captcha_mem))
        if not sms_captcha_mem or sms_captcha_mem != sms_captcha:
            raise ValidationError(message='短信验证码错误')

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        #因为图形验证码存储的key和值都是一样的，所以我们只要判断key是否存在就行
        if not xcache.get(graph_captcha.lower()):
            raise ValidationError(message='图形验证码错误')

#登陆表单
class SignInForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[35678]\d{9}',message='手机号码格式错误')])
    password = StringField(validators=[Length(5,30,message='密码格式错误')])
    remember = StringField()

class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题！')])
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id！')])

class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入评论内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id！')])

bbs/apps/common/views.py
from flask import Blueprint, make_response,request
from utils.captcha import Captcha
from io import BytesIO
import json
from utils import xcache

from utils.zzy_cms.zhenzismsclient import send_sms
from utils import xjson
from .forms import SmsCaptchaForm

from flask import jsonify
import qiniu

bp = Blueprint('common', __name__, url_prefix='/c')  #common太长，改为c

@bp.route('/')
def index():
    return 'common index'


@bp.route('/graph_captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    xcache.set(text.lower(), text.lower())  # 图片验证码这里，不好设置一个唯一的key,索性直接也用验证码的值作为key
    return resp


@bp.route('/sms_captcha/',methods=['POST'])
def sms_captcha():
    sms_captcha_form = SmsCaptchaForm(request.form)
    if sms_captcha_form.validate():
        telephone = sms_captcha_form.telephone.data
        #生成随机的验证，之前图片那里有方法实现了，我们直接调用就行，生成6位的验证码
        radom_code = Captcha.gene_text(6)
        cont = '测试bbs,您的验证码为：%s' % (radom_code)
        params = {'code': cont}
        result = send_sms(telephone, params)
        dict_res = json.loads(result)
        if dict_res['code'] == 0:
            xcache.set(telephone,radom_code) #把手机号作为key
            return xjson.json_success('短信发送成功')
        else:
            return xjson.json_server_error('短信发送失败')
    else:
        return xjson.json_params_error('参数错误')


# @bp.route('/uptoken/')
# def uptoken():
#     access_key = '4pMtV3F2eWZWv0TSD3DXjhcmlmVpxOCLvIdM8aF7'
#     secret_key = 'GsmHmllZkpxOh5VAkzGrSSjCL7MQGZraQhtYmE-O'
#     q = qiniu.Auth(access_key,secret_key)
#
#     bucket = 'flask-1902bbs'
#     token = q.upload_token(bucket)
#     return jsonify({'uptoken':token})

bbs/apps/front/__init__.py
from .views import bp

from apps.front import hooks

bbs/apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    g
)

from apps.front.decorators import login_required
from .forms import SignUpForm
from .models import FrontUser
from exts import db
from utils import xjson
from utils import safeutils
import config
from .forms import SignInForm
from .forms import AddPostForm
from apps.models import BannerModel, BoardModel, PostModel
from flask_paginate import Pagination, get_page_parameter
from flask import abort

from .forms import AddCommentForm
from apps.models import CommentModel

from apps.models import HighlightPostModel
from sqlalchemy.sql import func

# from .decorators import login_required

bp = Blueprint('front', __name__)

@bp.route('/')
def index():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    boards = BoardModel.query.all()
    # comments = CommentModel.query.all()

    # 当前页面
    page = request.args.get(get_page_parameter(), type=int, default=1)
    # 开始位置
    start = (page - 1) * config.PER_PAGE
    # 结束位置
    end = start + config.PER_PAGE

    board_id = request.args.get('bd', type=int, default=None)
    # comment_id = request.args.get('bd', type=int, default=None)
    sort = request.args.get("st", type=int, default=1)
    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精的时间倒叙排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞的数量排序,点赞功能没有做，所以这里用时间倒序排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论的数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    if board_id:
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()

    # if comment_id:
    #     query_obj = query_obj.filter(PostModel.comment_id == comment_id)
    #     posts = query_obj.slice(start, end)
    #     total = query_obj.count()
    # else:
    #     posts = query_obj.slice(start, end)
    #     total = query_obj.count()


    pagination = Pagination(bs_version=3,page=page, total=total)
    context = {
        'banners': banners,
        'boards': boards,
        # 'comments':comments,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort
    }
    return render_template('front/front_index.html', **context)



class SignUpViews(views.MethodView):
    def get(self):
        return render_template('front/front_signup.html')

    def post(self):
        signup_form = SignUpForm(request.form)
        if signup_form.validate():
            telephone = signup_form.telephone.data
            username = signup_form.username.data
            password = signup_form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return xjson.json_success('恭喜您，注册成功')
        else:
            return xjson.json_params_error(signup_form.get_error())


bp.add_url_rule('/signup/', view_func=SignUpViews.as_view('signup'))


class SignInViews(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        return render_template('front/front_signin.html')


    def post(self):
        signin_form = SignInForm(request.form)
        if signin_form.validate():
            telephone = signin_form.telephone.data
            password = signin_form.password.data
            remember = signin_form.remember.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.premanent = True
                return xjson.json_success('登陆成功')
            else:
                return xjson.json_params_error('手机号或密码错误')
        else:
            return xjson.json_params_error(signin_form.get_error())

bp.add_url_rule('/signin/', view_func=SignInViews.as_view('signin'))



@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        add_post_form = AddPostForm(request.form)
        if add_post_form.validate():
            title = add_post_form.title.data
            content = add_post_form.content.data
            board_id = add_post_form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return xjson.json_param_error(message='没有这个板块')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return xjson.json_success()
        else:
            return xjson.json_param_error(message=add_post_form.get_error())

@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)

@bp.route('/comment/',methods=['POST'])
@login_required
def add_comment():
    add_comment_form = AddCommentForm(request.form)
    if add_comment_form.validate():
        content = add_comment_form.content.data
        post_id = add_comment_form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return xjson.json_success()
        else:
            return xjson.json_param_error('没有这篇帖子！')
    else:
        return xjson.json_param_error(add_comment_form.get_error())

bbs/templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BBS论坛404页面</title>
</head>
<body>
    您要找的页面已经到火星去了~~
    <div>
        <a href="/">回到首页</a>
    </div>
</body>
</html>

bbs/templates/front/front_apost.html
{% extends "front/front_base.html" %}

{% block title %}
    发布帖子
{% endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='front/js/front_apost.js') }}"></script>
    <script src="{{ url_for('static',filename='common/layer-v3.1.1/layer/layer.js') }}"></script>

{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}

            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain" style="height:500px;"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>
{% endblock %}

bbs/templates/front/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='common/js/bbsajax.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='front/css/front_base.css') }}">

    <script src="{{ url_for('static',filename='ueditor/ueditor.config.js') }}"></script>
    <script src="{{ url_for('static',filename='ueditor/ueditor.all.min.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">luck的bbs论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('front.index') }}">首页</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="请输入关键字">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
{#            <li><a href="#">登录</a></li>#}
{#            <li><a href="#">注册</a></li>#}
              {% if g.front_user %}
                  <span id="login-tag" data-is-login="1" style="display:none;"></span>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ g.front_user.username }}
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#">个人中心</a></li>
                        <li><a href="#">设置</a></li>
                        <li><a href="{{ url_for('front.signup') }}">注销</a></li>
                      </ul>
                  </li>
              {% else %}
                  <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                  <li><a href="{{ url_for("front.signup") }}">注册</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="main-container">
         {% block body %}{% endblock %}

    </div>

</body>
</html>

bbs/templates/front/front_index.html
{% extends 'front/front_base.html' %}

{% block title %}首页-BBS论坛{% endblock %}

{% block head %}
    <link href="{{ url_for('static', filename='front/css/front_index.css') }}" rel="stylesheet">
{#    <link href="{{ url_for('static', filename='front/css/front_base.css') }}" rel="stylesheet">#}
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
              <!-- 指示器 -->
              <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" ></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
              </ol>

              <!-- 轮播图 class="active"-->
              <div class="carousel-inner" role="listbox">


                  {% for banner in banners %}
                  {% if loop.first %}
                      <div class="item active">
                  {% else %}
                      <div class="item">
                  {% endif %}
                      <a href="{{ banner.link_url }}">
                            <img src="{{ banner.image_url }}" alt="...">
                      </a>
                  </div>
                  {% endfor %}
              </div>

              <!-- 左右切换的控制按钮 -->
              <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
        </div>
    </div>




    <div class="sm-container">

        <div style="padding-bottom: 10px">
{#            <button class="btn btn-warning btn-block">发布帖子</button>#}
            <a href="{{ url_for("front.apost") }}" class="btn btn-warning btn-block">发布帖子</a>
        </div>

        <div class="list-group">
          <a href="/" class="list-group-item {% if not current_board %}active{% endif %}">所有板块</a>
          {% for board in boards %}
              <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item {% if current_board==board.id %}active{% endif %}">{{ board.name }}</a>
          {% endfor %}
        </div>


    </div>
 </div>


    <div class="post-group">
    <ul class="post-group-head">
            <li class="{% if current_sort==1 %}active{% endif %}"><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
            <li class="{% if current_sort==2 %}active{% endif %}"><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
            <li class="{% if current_sort==3 %}active{% endif %}"><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
            <li class="{% if current_sort==4 %}active{% endif %}"><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
    </ul>
    <ul class="post-list-group">
        {% for post in posts %}
            <li>
                <div class="author-avatar-group">
                    <img src="{{ post.author.avatar or url_for('static',filename='common/images/logo.jpg') }}" alt="">
                </div>
                <div class="post-info-group">
                    <p class="post-title">
                        <a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                        {% if post.highlight %}
                            <span class="label label-danger">精华帖</span>
                        {% endif %}
                    </p>
                    <p class="post-info">
                        <span>作者:{{ post.author.username }}</span>
                        <span>发表时间:{{ post.create_time }}</span>
                        <span>评论:0</span>
                        <span>阅读:0</span>
                    </p>
                </div>
            </li>
        {% endfor %}
    </ul>
    <div style="text-align: center">
    {{ pagination.links }}
    </div>
</div>

{% endblock %}

bbs/templates/front/front_pdetail.html
{% extends 'front/front_base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='front/css/front_pdetail.css') }}">
    <script src="{{ url_for('static',filename='common/layer-v3.1.1/layer/layer.js') }}"></script>
    <script src="{{ url_for('static',filename='ueditor/ueditor.config.js') }}"></script>
    <script src="{{ url_for('static',filename='ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ url_for('static',filename='front/js/front_pdetail.js') }}"></script>

{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-container">
            <h2>{{ post.title }}</h2>
            <p class="post-info-group">
                <span>发表时间：{{ post.create_time }}</span>
                <span>作者：{{ post.author.username }}</span>
                <span>所属板块：{{ post.board.name }}</span>
                <span>阅读数：{{ post.read_count }}</span>
                <span>评论数：0</span>
            </p>
            <article class="post-content" id="post-content" data-id="{{ post.id }}">
                {{ post.content|safe }}
            </article>
        </div>
        <div class="comment-group">
        <h3>评论列表</h3>
        <ul class="comment-list-group">
            {% for comment in post.comments %}
                <li>
                    <div class="avatar-group">
                        <img src="{{ comment.author.avatar or url_for('static', filename='common/images/logo.png') }}" alt="">
                    </div>
                    <div class="comment-content">
                        <p class="author-info">
                            <span>{{ comment.author.username }}</span>
                            <span>{{ comment.create_time }}</span>
                        </p>
                        <p class="comment-txt">
                            {{ comment.content|safe }}
                        </p>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="add-comment-group">
        <h3>发表评论</h3>
        <script id="editor" type="text/plain" style="height:100px;"></script>
        <div class="comment-btn-group">
            <button class="btn btn-primary" id="comment-btn">发表评论</button>
        </div>
    </div>

    </div>
    <div class="sm-container"></div>
{% endblock %}

bbs/templates/front/front_signbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title  %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='common/js/bbsajax.js') }}"></script>
    <script src="{{ url_for('static', filename='common/js/md5.js') }}"></script>
    <script src="{{ url_for('static', filename='common/js/bbsparams.js') }}"></script>
{#    <script src="{{ url_for('static', filename='front/js/front_signup.js') }}"></script>#}
    <script src="{{ url_for('static',filename='common/layer-v3.1.1/layer/layer.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    <div class="out-box">
        <h2 class="page-title">{% block h2_block %}{% endblock %}</h2>
        <div class="form-box">
            {% block form_content %}{% endblock %}
            <span style="display: none;" id="return-to-span">{{ return_to }}</span>
        </div>
    </div>
</body>
</html>

bbs/templates/front/front_signin.html
{% extends 'front/front_signbase.html' %}

{% block title %}登录-BBS论坛{% endblock %}

{% block head %}
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="{{ url_for('static', filename='front/js/front_signin.js') }}"></script>

      <style>
        body{
    background-color: #8CD4F5;
}
.page-title {
            text-align: center;
            padding-top: 50px;
}
.out-box{
    width: 845px;
    background-color: white;
    margin: 0 auto;
    margin-top: 50px;
}
.page-title {
    text-align: center;
    padding-top: 80px;
}
.form-box{
    padding-top: 50px;
    padding-bottom: 50px;
    width: 300px;
    margin: 0 auto;
}
</style>

{% endblock %}

{% block h2_block %}登录BBS论坛{% endblock %}

{% block form_content %}
    <div class="form-group">
        <input type="text" class="form-control" name="telephone" placeholder="手机号码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="remember" value="1">记住我
        </label>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
    </div>
    <div class="form-group">
        <a href="{{ url_for("front.signup") }}" class="signup-link">没有账号？立即注册</a>
        <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
    </div>
{% endblock %}

bbs/templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}





{% block title %}注册-BBS论坛{% endblock %}

{% block head %}
    <meta name="csrf-token" content="{{ csrf_token() }}">
{#<script src="{{ url_for('static', filename='front/css/sigup.css') }}"></script>#}
     <script src="{{ url_for('static', filename='front/js/front_signup.js') }}"></script>

    <style>
        body{
            background-color: #8CD4F5;
        }

        .page-title {
            text-align: center;
            padding-top: 50px;
        }
        .out-box{
            width: 845px;
            background-color: white;
            margin: 0 auto;
            margin-top: 50px;

        }

        .page-title {
            text-align: center;
            padding-top: 80px;
        }

        .form-box{
            padding-top: 50px;
            padding-bottom: 50px;
            width: 300px;
            margin: 0 auto;
        }
        .captcha-addon {
            padding: 0;  //这是内边距为0，因为input-group-addon有设置内边距
            overflow: hidden;   //当里面的元素超出则隐藏
        }

        #captcha-img{
            height: 32px;   //设置图片的高度为32px
            cursor: pointer;   //当鼠标移到图片上变成手的图标
        }
    </style>
{% endblock %}
{% block h2_block %}注册BBS论坛{% endblock %}

{% block form_content %}
    <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                    <span class="input-group-btn">
                        <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>
                    </span>
                </div>
            </div>
    <div class="form-group">
        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" placeholder="密码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="确认密码">
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
            <span class="input-group-addon captcha-addon">
                <img  id="captcha-img" src="{{ url_for('common.graph_captcha') }}">
            </span>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
    </div>
{% endblock %}